[package]
name = "fungibleAsset"
version = "1.0.0"
authors = []

[addresses]
  ownerAddress="1016ac9e1a3570cb2b67e2ec769c391b052658f5352450af279cb7253cb3b731"
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
